volumes:
  db-data:

services:
  web:
    build: .
    platform: linux/amd64
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
               bundle exec rails server -b '0.0.0.0'"

    ports:
      - '3000:3000'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    volumes:
      - .:/myapp
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:12
    platform: linux/amd64
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
